#!bash

FILE=./Career_Stats_Field_Goal_Kickers.csv

usage() {
	echo -e "Usage: "$0" <command> [<args>]\n"
	echo "mostMakes <NumLines>"
	echo -e "Print <NumLines> most productive FG kicking seasons\n"
	echo "mostAttempts <NumLines>"
	echo -e "Print <NumLines> most productive FG attempting seasons\n"
}

#Returns a list of the most productive FG kicking seasons by an NFL kicker
mostMakes() {
	tail -n 1994 $FILE | cut -d , -f 2,3,5,6,10 | sort -t , -k 5 -g -r | head -n "$1"
}

#Returns a list of the most productive FG attempting seasons by an NFL kicker
mostAttempts() {
	tail -n 1994 $FILE | cut -d , -f 2,3,5,6,11 | sort -t , -k 5 -g -r | head -n "$1"
}

if [[ $# -eq 0 ]] ; then
	usage
	exit 1
fi

"$@"
