#! bash

FILE1=./GMFGmostMakes.expected
FILE2=./GMFGmostAttempts.expected

usage() {
	echo -e "Usage: ./kickerAppTester <command>\n"
	echo "testGMFG"
	echo -e "Tests the getMostFieldGoals program\n"
}

testGMFG() {
	echo "testing 1/2"
	./getMostFieldGoals mostMakes 5 > GMFGmostMakes.actual
	cmp $FILE1 GMFGmostMakes.actual || echo "mostMakes test failed"

	echo "testing 2/2"
	./getMostFieldGoals mostAttempts 5 > GMFGmostAttempts.actual
	cmp $FILE2 GMFGmostAttempts.actual || echo "mostAttempts test failed"

	rm GMFGmostAttempts.actual
	rm GMFGmostMakes.actual
}

if [[ $# -eq 0 ]] ; then
	usage
	exit 1
fi

$@
