#! bash

FILE1=./GMFGmostMakes.expected
FILE2=./GMFGmostAttempts.expected

FILE3=./NTKcountTimes.expected
FILE4=./NTKmostRecentYear.expected

usage() {
	echo -e "Usage: ./kickerAppTester <command>\n"
	echo "testGMFG"
	echo -e "Tests the getMostFieldGoals program\n"
	echo "testNTK"
	echo "Tests the numTimesKicked program"
}

testGMFG() {
	echo "testing 1/2"
	./getMostFieldGoals mostMakes 5 > GMFGmostMakes.actual
	cmp $FILE1 GMFGmostMakes.actual || echo "mostMakes test failed"

	echo "testing 2/2"
	./getMostFieldGoals mostAttempts 5 > GMFGmostAttempts.actual
	cmp $FILE2 GMFGmostAttempts.actual || echo "mostAttempts test failed"

	rm GMFGmostAttempts.actual
	rm GMFGmostMakes.actual
}

testNTK() {
	echo "testing 1/2"
	./numTimesKicked countTimes 30 > NTKcountTimes.actual
	cmp $FILE3 NTKcountTimes.actual || echo "countTimes test failed" 

	echo "testing 2/2"
	./numTimesKicked mostRecentYear 30 > NTKmostRecentYear.actual
	cmp $FILE4 NTKmostRecentYear.actual || echo "mostRecentYear test failed"

	rm NTKcountTimes.actual
	rm NTKmostRecentYear.actual
}

if [[ $# -eq 0 ]] ; then
	usage
	exit 1
fi

$@
