#! bash

FILE=./Career_Stats_Field_Goal_Kickers.csv

usage() {
	echo "Usage: "$0" <command> [<args>]"
	echo
	echo "countTimes <fieldGoalsKicked>"
	echo "Print number of times player has kicked exactly <fieldGoalsKicked> in a season"
}

countTimes() {
	cat $FILE | cut -d , -f 10 | grep "$1" -w | uniq -c
}

mostRecentYear() {
	cat $FILE | cut -d , -f 5,10 | grep "$1$" | cut -d , -f 1 | sort -g -r | head -n 1
}

if [[ $# -eq 0 ]] ; then
	usage
	exit 1
fi

"$@"
