#! bash

FILE=./Career_Stats_Field_Goal_Kickers.csv

usage() {
	echo "Usage: "$0" <command> [<args>]"
	echo
	echo "countTimes <fieldGoalsKicked>"
	echo "Print number of times player has kicked exactly <fieldGoalsKicked> in a season"
	echo
	echo "mostRecentYear <fieldGoalsKicked>"
	echo "Print most recent year a player kicked exactly  <fieldGoalsKicked> in a season"

}

#Returns the number of times a quantity of field goals was kicked as well as the quantity of field goals
countTimes() {
	cat $FILE | cut -d , -f 10 | grep "$1" -w | uniq -c
}

#Returns the most recent year a quantity of field goals was kicked
mostRecentYear() {
	cat $FILE | cut -d , -f 5,10 | grep "$1$" | cut -d , -f 1 | sort -g -r | head -n 1
}

if [[ $# -eq 0 ]] ; then
	usage
	exit 1
fi

"$@"
